### ISSUE TITLE
Unable to init new provider from registry

### ISSUE THREAD

**Issue by eloo** [cloudfoundry-community/terraform-provider-cloudfoundry#280]
Hi,
i've just seen that the provider is now part of the registry as a community-provider. 
Really cool!

But so far i have trouble of using it. 

terraform init is going to produce the following for me:
```
Initializing provider plugins...
- Finding hashicorp/null versions matching "~> 2.0"...
- Finding cloudfoundry-community/cloudfoundry versions matching "0.12.4"...
- Finding latest version of hashicorp/archive...
- Finding latest version of hashicorp/external...
- Finding latest version of hashicorp/cloudfoundry...
- Installing hashicorp/null v2.1.2...
- Installed hashicorp/null v2.1.2 (signed by HashiCorp)
- Installing cloudfoundry-community/cloudfoundry v0.12.4...
- Installed cloudfoundry-community/cloudfoundry v0.12.4 (self-signed, key ID 7D2C9F0DEADEE1C2)
- Installing hashicorp/archive v1.3.0...
- Installed hashicorp/archive v1.3.0 (signed by HashiCorp)
- Installing hashicorp/external v1.2.0...
- Installed hashicorp/external v1.2.0 (signed by HashiCorp)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Error: Failed to install provider

Error while installing hashicorp/cloudfoundry: provider registry
registry.terraform.io does not have a provider named
registry.terraform.io/hashicorp/cloudfoundry
```

Setup:
```
terraform --version
Terraform v0.13.2
+ provider registry.terraform.io/cloudfoundry-community/cloudfoundry v0.12.4
+ provider registry.terraform.io/hashicorp/archive v1.3.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
```
terraform.tf
```
terraform {
  required_version = ">= 0.13"
  required_providers {
    cloudfoundry = {
      source  = "cloudfoundry-community/cloudfoundry"
      version = "0.12.4"
    }
    archive = {
      source = "hashicorp/archive"
    }
    external = {
      source = "hashicorp/external"
    }
    null = {
      source = "hashicorp/null"
    }
  }
}
```
provider.tf
```
provider "cloudfoundry" {
  api_url = var.cf_api_url
  user = data.external.credentials.result.user
  password = data.external.credentials.result.password
  skip_ssl_validation = false
  default_quota_name = "small"
}
```

What have i tested already?
* Migrated the provider version to the required_providers block (as you can see above)
* terraform 0.13upgrade (has changed some resources and so on)
* `terraform state replace-provider registry.terraform.io/hashicorp/cloudfoundry registry.terraform.io/cloudfoundry-community/cloudfoundry` resulted in `No matching resources found.`
* `terraform state replace-provider registry.terraform.io/-/cloudfoundry registry.terraform.io/cloudfoundry-community/cloudfoundry` resulted in `No matching resources found.`
* Checked my state if there is something like hashicorp/cloudfoundry or -/cloudfoundry -> nothing found
* Removed `.terraform`, `~/.terraformrc` and `~/.terraform.d/`

I really don't know where the problem comes from :(

Hopefully you guys can help me
Thanks

**Comment by ArthurHlt** [comment]
I could reproduce by creating an old format and follow upgrade and I was able to fix it. This error happens when you have to migrate in terraform 0.13. This is what I get as error:
```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Using previously-installed hashicorp/external v1.2.0
- Using previously-installed hashicorp/null v2.1.2
- Using previously-installed cloudfoundry-community/cloudfoundry v0.12.4
- Using previously-installed hashicorp/archive v1.3.0
- Finding latest version of -/cloudfoundry...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider -/cloudfoundry:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/-/cloudfoundry
```

Here steps to fix this:

```bash
$ terraform 0.13upgrade
$ terraform state replace-provider registry.terraform.io/-/cloudfoundry registry.terraform.io/cloudfoundry-community/cloudfoundry
$ terraform init
```

I'm closing for now but feel free to open if you still have an problem

**Comment by eloo** [comment]
Sadly this does not fix my problem.
I'm getting `No matching resources found.`
Also i have already mentioned that i had done exactly the same :( 
It looks also that your problem is a little bit different as you in your error the provider is named `registry.terraform.io/-/cloudfoundry`

and in my case its `registry.terraform.io/hashicorp/cloudfoundry`

Any ideas?

**Comment by loafoe** [comment]
@eloo what does `terraform providers` produce as output? That should tell you where these (bogus) dependencies are coming from. We struggled a bit with this as well but all issues were resolved eventually by `state replace-provider` calls

**Comment by eloo** [comment]
@loafoe omg i was looking for such a command the whole time :D

but in the meantime i've isolated the issue to a specific setup.. which is also stated by the providers command

```
terraform providers
Providers required by configuration:
.
├── provider[registry.terraform.io/cloudfoundry-community/cloudfoundry] 0.12.4
└── module.test-module
    └── provider[registry.terraform.io/hashicorp/cloudfoundry]
```

AFAIK the problem is related when you use modules.
I dont know why but terraform is then not applying the community plugin (maybe i missed a configuration for modules?)

to reproduce you can set it up like this
```
terraform.tf

terraform {
  required_version = ">= 0.13"
  required_providers {
    cloudfoundry = {
      source  = "cloudfoundry-community/cloudfoundry"
      version = "0.12.4"
    }
  }

---
app-module.tf

module "test-module" {
  source = "./module"
}

---
module/test-module.tf

resource "cloudfoundry_app" "spring-music" {
    name = "spring-music"
    path = "/Work/cloudfoundry/apps/spring-music/build/libs/spring-music.war"
}
```

**Comment by loafoe** [comment]
@eloo in the module itself you should also specify the provider mapping e.g. 

```hcl
terraform {
  required_version = ">= 0.13.0"

  required_providers {
    cloudfoundry = {
      source  = "cloudfoundry-community/cloudfoundry"
      version = ">= 0.12.4"
    }
  }
}
```
