### ISSUE TITLE
CF-DatabaseError when concurrently creating routes using V2 API calls

### ISSUE THREAD

**Issue by loafoe** [cloudfoundry-community/terraform-provider-cloudfoundry#286]
We've been experiencing random `apply` failures recently and some investigation has led to a theory where a number of concurrent calls to `POST /v2/routes` by the provider seem to cause the following generic, not so useful, error from Cloud foundry:

`HTTP 500 Internal Server Error`

```json
{
  "code": 10011,
  "description": "Database error",
  "error_code": "CF-DatabaseError"
}
```

Testing a small change that serializes these calls via `Mutex` but curious to hear if others are running into this and if it makes sense to pursue upstream CF investigation/fix seeing as the `V2` API is close to deprecation.

There is also code that suggests a retry mechanism is in place:

https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/8b5561dde9b3942800aa89410e4ac8efc690379e/cloudfoundry/managers/session.go#L150-L166

But debug output does not show any retry being performed on the `HTTP 500` ?

**Comment by loafoe** [comment]
POSTs are not retried:

https://github.com/cloudfoundry/cli/blob/ec7d58c7338bb97f8b8f753fa44bb945f60fac80/api/plugin/wrapper/retry_request.go#L60-L69

**Comment by ArthurHlt** [comment]
if i remember well, route creation is pretty async thing on cloud foundry. Could you show me your terraform which cause this issue ?

For the post not retrying, i just didn't wanted to retry on an failed creation for behaviour which can occur by doing that. not sure if it is really clear

**Comment by loafoe** [comment]
@ArthurHlt  the code is available here:

https://github.com/philips-labs/terraform-cloudfoundry-thanos/blob/8252d28ee6351150920a2073a740059fcc8ae6c9/thanos_store.tf#L21-L27

It's indeed very async because the error goes away if we enable provisioning of a database inside this module which takes up to 10 mins. After some more testing, it turns out the route is in fact created successfully, despite the CF API returning CF-DatabaseError, argh!  So I'm now trying out some code that tries to read the route before giving up.

**Comment by loafoe** [comment]
@ArthurHlt I created a PR #288 which resolves the issue by adding a retry only under this condition. I looked at a more generic solution but ideally this retry should go away once the switch to the hopefully better CF V3 API is done.

**Comment by ArthurHlt** [comment]
thanks for the nice catch and PR, i'm closing it
