### ISSUE TITLE
Control order of bindings

### ISSUE THREAD

**Issue by foudelsalhi** [cloudfoundry-community/terraform-provider-cloudfoundry#290]
I have a CF application that requires the XSUAA service binding before binding Job Scheduler service. This has been controlled using terraform 0.11 and [cf provider 0.9.14 ](https://github.com/chrismathias/terraform-provider-cf/releases/tag/0.9.14) as below: 
```
  service_binding = [
    {
      service_instance = "${var.service_instance_id_xsuaa_internal}"
    },
    {
      service_instance = "${var.service_instance_id_jobscheduler}"
    },
    {
      service_instance = "${var.service_instance_id_xsuaa_external}"
    }
    ]
```
Within terraform 0.12 and the  [cloud foundry terraform provider 0.12.6](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/releases/tag/v0.12.6) community version, the syntax looks as below:
```
  service_binding {
    service_instance = var.service_instance_id_xsuaa_external
  }
  service_binding {
    service_instance = var.service_instance_id_jobscheduler
  }
  service_binding {
    service_instance = var.service_instance_id_xsuaa_internal
  }
```

When applying, I get the below error that comes from our job scheduler service:

`Error: Service broker error: Service broker jobscheduler-broker failed with: No xsuaa service instance bound to the application. Please bind xsuaa service instance to the application before binding jobscheduler service instance.`

Is there a way to control the order of the bindings?

**Comment by ArthurHlt** [comment]
Thanks for the PR, i'm closing this issue
