### ISSUE TITLE
Removing a hostname on an existing route is not working

### ISSUE THREAD

**Issue by vigneshmsft** [cloudfoundry-community/terraform-provider-cloudfoundry#291]
I recently tried to update(remove the hostname) the hostname of an existing route.

So I have the below setup and initially created a route for my app using the below block
```
data cloudfoundry_domain my_domain {
  name = "domain.com"
}

resource cloudfoundry_route web_app_route {
  domain   = data.cloudfoundry_domain.my_domain.id
  space    = data.cloudfoundry_space.space.id
  hostname = var.web_app_host_name
}
```

Then later decided that we no longer need to have the app available on the `www` hostname in one of the environments (spaces), 
so re-ran terraform passing a null value for the `var.web_app_host_name` variable.

terraform plan came up with the correct plan and indicated the hostname would be removed from the route
`- hostname "www" -> null`
But once I went in to confirm (after `apply`), the route still had the old hostname.
I ran `tf apply` again and it still came up with the correct plan but the hostname was not removed.

I manually deleted the route (from the cli) and reran terraform to apply the new route(without the hostname) again.

`Terraform 0.13.5 & cf provider: 0.12.6`

Thanks

**Comment by loafoe** [comment]
@vigneshmsft to remove the route you would need to remove the resource definition itself and rerun Terraform. You can also remove it with `terraform destroy -target=cloudfoundry_route.web_app_route` but then it would be recreated on the next apply. Looks like the `null` name simply does nothing right now. The provider should probably error on that.

**Comment by vigneshmsft** [comment]
My intention was not to remove the route but amend the route by removing the hostname part of it, akin to creating a route using `cf create-route   domain.com`. 
The above block allows me the flexibility of having hostnames

**Comment by ArthurHlt** [comment]
thanks for the feedback, this has now been fixed in the PR above, i'm closing this issue
