### ISSUE TITLE
Docker apps are not always restarted on environment changes

### ISSUE THREAD

**Issue by loafoe** [cloudfoundry-community/terraform-provider-cloudfoundry#294]
We noticed that Docker apps are not restarted when the only change is in the environment. This means changes are not picked up and we have to manually restart these apps. A small PR is upcoming on the code below:

https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/8b5561dde9b3942800aa89410e4ac8efc690379e/cloudfoundry/resource_cf_app.go#L582-L586

**Comment by loafoe** [comment]
adding `|| d.HasChange("environment")` should solve this

**Comment by ArthurHlt** [comment]
Thanks for the PR i\m closing this issue
