### ISSUE TITLE
`id_bg` not updated as part of blue/green Docker app update

### ISSUE THREAD

**Issue by vlaurin** [cloudfoundry-community/terraform-provider-cloudfoundry#311]
**terraform**: 0.13.6
**terraform-provider-cloudfoundry**: 0.13.0

We have a `cloudfoundry_app` deploying a Docker image using the `blue-green-v2` strategy.

The issue is that when an update of the app is required, for example because the `docker_image` and/or the `environment` was changed, the generated diff does not flag `id_bg` as an attribute being updated. Below is a recent example of an update, triggered by both `docker_image` and `environment` changes:

```terraform
  # cloudfoundry_app.anti_virus will be updated in-place
  ~ resource "cloudfoundry_app" "anti_virus" {
        disk_quota           = 1024
        docker_credentials   = (sensitive value)
      ~ docker_image         = "ghcr.io/[...]/docker-clamav:66cf97a" -> "ghcr.io/[...]/docker-clamav:66250e8"
        enable_ssh           = true
      ~ environment          = (sensitive value)
        health_check_timeout = 0
        health_check_type    = "port"
        id                   = "e6637970[...]e98c968eb3f9"
        id_bg                = "e6637970[...]e98c968eb3f9"
        instances            = 1
        memory               = 3072
        name                 = "anti-virus"
        ports                = [
            3310,
        ]
        space                = "a2e86cf2[...]1ecc178f8a6b"
        stack                = "a7ed64d9[...]86849c8e30de"
        stopped              = false
        strategy             = "blue-green-v2"
        timeout              = 120

        routes {
            port  = 3310
            route = "03c6172c[...]5cf4a1d2252d"
        }
    }
```

However, during the update CloudFoundry restages the application, causing a new GUID to be generated for the application. As a result, resources depending on `id_bg` will be out of sync. This is for example the case of network policies referencing `id_bg` as either a source or a destination.

I believe the expected behaviour would be for `id_bg` to be marked as "known after apply":
```terraform
        id_bg                = "e6637970[...]e98c968eb3f9" -> (known after apply)
```

I'm not familiar with Go, but I wonder if the issue is somehow the result of the following block being skipped: https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/8e6fe5710b21c39cabdf6ef3604012de26a03757/cloudfoundry/resource_cf_app.go#L247-L251

**Comment by loafoe** [comment]
@vlaurin that could very well be as the `restage` step should actually be skipped for Docker images, so the logic should not be here.

**Comment by vlaurin** [comment]
@loafoe Please forgive me if I'm mistaken, but for the blue/green strategy to be respected, wouldn't we always end-up with a new GUID? My understanding is that the existing app first get renamed with the `-venerable` suffix, then a new app is created with the exact name and the new docker image; and finally the `-venerable` app is destroyed. As such, I cannot see how the `id_bg` could stay the same during the deployment.

I believe the above is the reason why the `IsCreateNewApp()` function of the blue/green deployer is implemented to always return `true`.

**Comment by loafoe** [comment]
@vlaurin TBH I have not explored the source or usage of the blue-green feature extensively, but you are right, the `id_bg` should change every time. The `IsCreateNewApp()` should be a condition in the expression itself I think. As it stands now it is ignored if `IsAppCodeChange(diff)` is false, which is the case if you use Docker..

**Comment by vlaurin** [comment]
It is ignored if `IsAppCodeChange(diff)` is false; but it shouldn't be ignored if `IsAppRestartNeeded(diff)` is true. That's because `isAppRestartNeeded(diff)` checks for `diff.HasChange("docker_image")`. So I think that part is actually correct as is.

Looking at it again, the issue actually comes from the beginning of the `CustomizeDiff` function:
https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/8e6fe5710b21c39cabdf6ef3604012de26a03757/cloudfoundry/resource_cf_app.go#L231-L241

When either `docker_image` or `path` have changed but their previous value was a non-empty string, the function returns immediately with `return nil` at line 240. As a result, the rest of the function where the need for a restart or restage is evaluated is never executed.

The fix would simply be to remove that `return nil` at line 240 to allow further customisation of the `diff` to take place, including the `diff.SetNewComputed("id_bg")` I'm after.

I'm going to try that change locally, hope that makes sense.

**Comment by vlaurin** [comment]
I've tested locally and it does behave as expected: with that change `id_bg` is correctly flagged as `(known after apply)` and resources depending on it are marked for update.

I've raised a PR, I hope it can be included in a future patch/minor version of the provider.

**Comment by loafoe** [comment]
@vlaurin I'm curious if you ran into #315 as well. That was an immediate show stopper for me when switching to blue-green so I'm keen finding if others are experiencing the same.

**Comment by vlaurin** [comment]
@loafoe that's quite possible, though I can't remember for sure. Our initial deployments were a year ago and we haven't done a fresh one since; but we did have that pattern of initial deployment failing and only succeeding on second run.

**Comment by loafoe** [comment]
That's exactly the behaviour I'm seeing. I created a tiny patch to fix that, it simply ensures `id_bg` always has a value (even for the day 1 deployment)
