### ISSUE TITLE
data.cloudfoundry_service "space" argument generates invalid query URL

### ISSUE THREAD

**Issue by mogul** [cloudfoundry-community/terraform-provider-cloudfoundry#319]
(Very similar to [the bug reported here](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/issues/249)...)

Using the [`space` parameter on `data.cloudfoundry_service`](https://registry.terraform.io/providers/cloudfoundry-community/cloudfoundry/latest/docs/data-sources/service#space) results in generation of an invalid query URL.

## What I tried

```
data "cloudfoundry_service" "k8s" {
  name  = "aws-eks-service"
  space = data.cloudfoundry_space.broker_space.id
}
```

## What I expected to happen

`data.cloudfoundry_service.k8s` would refer to the `aws-eks-service` service offered by the space-scoped broker registered in `data.cloudfoundry_space.broker_space`.

## What happened instead

In the `terraform plan` result I see:

```
Error: The query parameter is invalid: space_guid

  on main.tf line 51, in data "cloudfoundry_service" "k8s":
  51: data "cloudfoundry_service" "k8s" {
```

## What I noticed when I investigated

With `TF_LOG=trace`, this is what I saw in the relevant section of the plan logs; note the **_highlighted_** line:

> 2021/03/20 18:42:33 [TRACE] vertex "data.cloudfoundry_service.k8s": starting visit (*terraform.NodePlannableResourceInstance)
> 2021/03/20 18:42:33 [TRACE] ReadResourceInstanceState: reading state for data.cloudfoundry_service.k8s
> 2021/03/20 18:42:33 [TRACE] EvalReadData: Re-validating config for data.cloudfoundry_service.k8s
> 2021/03/20 18:42:33 [TRACE] GRPCProvider: ValidateDataSourceConfig
> 2021/03/20 18:42:33 [TRACE] EvalReadData: data.cloudfoundry_service.k8s configuration is complete, so reading from provider
> 2021/03/20 18:42:33 [TRACE] GRPCProvider: ReadDataSource
> 2021-03-20T18:42:33.288Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 REQUEST: [2021-03-20T18:42:33Z]
> **_2021-03-20T18:42:33.288Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 GET /v2/services?q=label%3Aaws-eks-service&q=space_guid%3A9a1db116-0180-42be-8ffa-7944dcf6bf50 HTTP/1.1_**
> 2021-03-20T18:42:33.288Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 host: api.fr.cloud.gov
> 2021-03-20T18:42:33.288Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 Accept: application/json
> 2021-03-20T18:42:33.288Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 User-Agent: terraform-provider/0.0.0-unknown-version (go1.14; amd64 linux)
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 RESPONSE: [2021-03-20T18:42:33Z]
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 HTTP/1.1 400 Bad Request
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 Connection: keep-alive
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 Content-Length: 123
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 Content-Type: application/json;charset=utf-8
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 Date: Sat, 20 Mar 2021 18:42:33 GMT
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 Strict-Transport-Security: max-age=31536000
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 X-Content-Type-Options: nosniff
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 X-Frame-Options: DENY
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 X-Vcap-Request-Id: 7a651cfc-b8a7-4671-6843-5faf28cfee9d::fde39c3b-226b-4142-8078-ce9b37813200
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 X-Xss-Protection: 1; mode=block
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 2021/03/20 18:42:33 {
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0:   "code": 10005,
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0:   "description": "The query parameter is invalid: space_guid",
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0:   "error_code": "CF-BadQueryParameter"
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: }
> 2021-03-20T18:42:33.499Z [DEBUG] plugin.terraform-provider-cloudfoundry_v0.13.0: 

There seems to be two problems with that generated query: 

1. The `q` parameter is set twice, once for each filter, rather than concatenating the filters.
2. `space_guid` is in fact not among the [valid query parameters for `/v2/services`](https://apidocs.cloudfoundry.org/15.3.0/#services)! ([The V3 API docs do list `space_guids` (plural)](http://v3-apidocs.cloudfoundry.org/version/3.97.0/index.html#list-service-offerings), but I don't believe this provider is using the V3 API.)

I tried to find the relevant code to make a PR, but couldn't locate [the code that implements mapping the filter to the query parameter](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/6b2314d5408f788ced01a6553752195fe2d51ff8/cloudfoundry/data_source_cf_service.go#L57), and it seems like this parameter isn't valid until V3 is in use in any case.

* In the short-term I suggest removing the documentation and this argument from the resource (since it doesn't map to the API).
* In the longer-term I suggest adding back a `spaces` argument, which takes a list and uses the V3 API and the `space_guids` query parameter to do the work.

**Comment by ArthurHlt** [comment]
thanks for found this non working feature (which is sad to see just now)

For the point 1, that's actually a valid parameter, this is how cloud foundry is waiting parameter to have a list.
That's actually quite common on uri but normally we use an another "shape" to say "hey this query parameter is a list". If cloud foundry was following what everyone do `q` would become `q[]`. And yes for your curiosity `q[]` is treated as query name, query parameters are, in fact, always a list of values.

So here, only the point 2 was a real problem which I have fixed in PR #334

**Comment by loafoe** [comment]
@mogul are you able to confirm this issue is addressed in the latest release? Do we still need to modify the documentation?

**Comment by mogul** [comment]
Confirmed! No need to modify the docs now that it works as expected.
