### ISSUE TITLE
resource service_key incorrectly documents argument as json_params

### ISSUE THREAD

**Issue by vigneshmsft** [cloudfoundry-community/terraform-provider-cloudfoundry#330]
The documentation for [service_key](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/master/docs/resources/service_key.md), incorrectly lists the argument name for json parameters as `json_params` instead of `params_json`

Resolution: please fix the typo in the documentation to use the correct argument name (`params_json`) from [resource_cf_service_key.go](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/master/cloudfoundry/resource_cf_service_key.go#L42) or rename the argument in code to `json_params` to keep it consistent with other resource arguments.

Happy to raise a PR if changing the typo in the documentation is the desired action.

**Comment by saliceti** [comment]
Shall we fix the documentation for now?

**Comment by dishantkamble** [comment]
When will this correction be available?

**Comment by loafoe** [comment]
@dishantkamble I will bake a release shortly
