### ISSUE TITLE
Resource: docker image not updated with blue-green strategy on v0.14.0

### ISSUE THREAD

**Issue by kicferk1** [cloudfoundry-community/terraform-provider-cloudfoundry#336]
Hello!

I have a terraform setup with cloudfoundry, using this repo as the source. 
We use docker images that we store on dockerhub. When we want to deploy, we `terraform apply` and everything works like a charm.

Until 3 days ago that is. Since then our builds are passing, but the docker image is not actually getting updated.

I spent a while digging into what's going on, why, and how to fix it, and here's what I found:
1. This seems to be an issue in version `0.14.0`, but not in version `0.13.0`
2. It only occurs with `blue-green-v2` deployment strategy. Changing it to `standard` fixed my issue. 

I haven't read through the code enough to understand exactly what's going on, but maybe it's to do with the fix for https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/issues/309? That seems like the only commit between the versions vaguely relating to what I'm seeing now.

**Comment by vlaurin** [comment]
I'm seeing the same behaviour: with blue-green deployment strategy docker images are not being updated since upgrade to v0.14.0.

@loafoe Fix #309 does seem the most likely culprit. Should it be a case of only skipping the restage step when the deployment strategy is standard you think? Would that still give you the behaviour you expected with the fix?

**Comment by loafoe** [comment]
@vlaurin @kicferk1 I will test with `blue-green-v2` . It could very well be that the "fix" caused a regression under some conditions. The conditional flow is non trivial and checks happens in various layers of the abstraction so I did not test all possible scenario's for sure.

**Comment by loafoe** [comment]
@vlaurin @kicferk1 when you upgrade your docker image, does the `docker_image` change the tag or are you using `latest` ? Just trying to narrow the test cases.. thx

**Comment by vlaurin** [comment]
> @vlaurin @kicferk1 when you upgrade your docker image, does the `docker_image` change the tag or are you using `latest` ? Just trying to narrow the test cases.. thx
> 

Always different tags. We've tried `latest` in lower envs but it has proven unreliable.

Please let me know if you need help looking into it, happy to help.

**Comment by kicferk1** [comment]
I think we are doing both (commit hashes for dev environments and named tags for production), but the case I tracked down was definitely with with variable tags.

**Comment by loafoe** [comment]
@kicferk1 @vlaurin confirmed the regression, sorry for for this! 

@ArthurHlt can you please merge #337 and create a new release. This fixes the `blue-green` strategy which was broken by my attempt at fixing #309

**Comment by vlaurin** [comment]
@loafoe No worries, thank you for looking into it, much appreciated.

**Comment by loafoe** [comment]
thanks @ArthurHlt  for quick release! @vlaurin @kicferk1 please try the `v0.14.1` release.

**Comment by kicferk1** [comment]
Looks like it works, thanks!

**Comment by vlaurin** [comment]
Yes, same here, `0.14.1` is working as expected. Thanks!
