### ISSUE TITLE
Blue-green causing database request failures

### ISSUE THREAD

**Issue by saliceti** [cloudfoundry-community/terraform-provider-cloudfoundry#353]
We run dozens of deployments per day using the blue-green strategy and frequently (410 errors over the past week) get various database permission errors a for a few seconds during the deployment, such as `PG::InsufficientPrivilege: ERROR:  permission denied for table features`. This error is emitted at the time of the blue-green deployment, from the app_id of the venerable app.
This impacts users as well as background jobs.

This is on the GOV.UK PaaS which uses the [paas RDS broker](https://github.com/alphagov/paas-rds-broker) for database services.

Could it be that the service binding is removed or the credentials are invalidated on the venerable app before the new app receives 100% of the traffic?

**Comment by loafoe** [comment]
@saliceti it sounds like a race condition where the venerable app or background task is still processing some request while the Unbind step is initiated by the provider. The broker you mentioned immediately drops the user credentials on Unbind:

https://github.com/alphagov/paas-rds-broker/blob/0ea4735a75de34fce80683a43f2b6332d66a8210/rdsbroker/broker.go#L849

I'm not quite sure how this can be prevented / solved in the provider itself?!

**Comment by loafoe** [comment]
Should be fixed in `v0.15.4+`
