### ISSUE TITLE
cloundfoundry app resource is always getting created(replaced) even if the app is already running and is part of the state file and there is no change in the resource

### ISSUE THREAD

**Issue by abalas4** [cloudfoundry-community/terraform-provider-cloudfoundry#375]
Cloundfoundry app resource is always getting created(Resource is being replaced) even if the cf app is already running and is part of the state file and there is no change in the app resource. When we do app upgrades, we typically leave the old app running, deploy the new app, certify the new app and then switch routes(map route to the new app, un map route from the old app and stop/delete the old  app) so that there is no down time for the consumers. I also dont see a way to unmap routes(Implementation of cf cli unmap-route command) from an existing app with the provider. Can the above features be provided?

**Comment by loafoe** [comment]
@abalas4 this feature is provided through the `routes` block. However, what is missing is the verification step that you perform. You can leverage the `blue-green` deployment method. This will prevent downtime but will not allow you to do any validation before doing the switchover. I would consider that out-of-scope for the provider at this time.
