### ISSUE TITLE
HEALTH_CHECK_TYPE failing for `none`

### ISSUE THREAD

**Issue by aswin-in-philips** [cloudfoundry-community/terraform-provider-cloudfoundry#430]
Cloud foundry provider version (v0.50.1) is failing with health_check_type "none" with below error.

 Error: Health check type must be "port", "process", or "http"

As per the official [documentation](https://registry.terraform.io/providers/cloudfoundry-community/cloudfoundry/latest/docs/resources/app#health_check_type) it takes the value "none".

**Comment by loafoe** [comment]
Quick glance shows `processUpdate` info is collected but not applied:

https://github.com/cloudfoundry-community/terraform-provider-
cloudfoundry/blob/1a1020356e799fde1e52bc5d03455890d41b58af/cloudfoundry/resource_cf_app.go#L492

**Comment by Thanhphan1147** [comment]
@aswin-in-philips for health_check_type 'none', this behavior is changed in v3 API and no longer accepting "none", so I think we only need to update the documentation http://v3-apidocs.cloudfoundry.org/version/3.126.0/#the-process-object
