### ISSUE TITLE
resource_cf_app accepts stack name instead of stack id

### ISSUE THREAD

**Issue by sleungcy** [cloudfoundry-community/terraform-provider-cloudfoundry#444]
It seems that the resource_cf_app api has been changed to accept the name of the stack, rather than the GUID of the stack. Which is now different from the wiki documentation:
https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/wiki/resource_app

**Comment by Thanhphan1147** [comment]
Hi, I updated the wiki
