### ISSUE TITLE
CF_TRACE does not log v3 api calls

### ISSUE THREAD

**Issue by sleungcy** [cloudfoundry-community/terraform-provider-cloudfoundry#450]
Hi,

I am not sure if I am doing something wrong, when I set CF_TRACE=debug.log, I do not see any api calls related to the v3 endpoints, but I do see the below api calls in the log during the plan & apply phase..

This would mean the CF_TRACE variable is picked up correctly, but somehow only the v3 calls are not recorded. 

```
> grep -P "^GET |^POST |^PATCH |^PUT |^DELETE" debug.log

GET /v2/info HTTP/1.1
GET / HTTP/1.1
GET /login HTTP/1.1
POST /oauth/token HTTP/1.1
GET /v2/info HTTP/1.1
GET / HTTP/1.1
GET /login HTTP/1.1
POST /oauth/token HTTP/1.1
```

Do you have idea where I should look into this issue?

**Comment by Thanhphan1147** [comment]
I think the relevant env variable to the provider is TF_LOG=(debug | info). CF_TRACE is mentioned in the cf cli but I'm not yet sure how this variable is used

**Comment by sleungcy** [comment]
The usage of CF_TRACE is mentioned in the Readme.md
https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry#testing-the-provider

**Comment by sleungcy** [comment]
Indeed, debug logging should use TF_LOG=debug
