### ISSUE TITLE
The terraform-provider-cloudfoundry_v0.15.0 plugin crashed!

### ISSUE THREAD

**Issue by SelesAbraham** [cloudfoundry-community/terraform-provider-cloudfoundry#465]
I am trying to apply terraform. When it applies changes I get plugin issue as mentioned below. Any inputs? Thanks 

The version used is v1.1.7

> The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
> Releasing state lock. This may take a few moments...
> Stack trace from the terraform-provider-cloudfoundry_v0.15.0 plugin:
> panic: Invalid diagnostic: empty summary. This is always a bug in the provider implementation
> Error: The terraform-provider-cloudfoundry_v0.15.0 plugin crashed!

![image](https://user-images.githubusercontent.com/30854461/223701573-71bda629-e01a-4567-bcdd-44aefb9d5e27.png)

**Comment by loafoe** [comment]
@SelesAbraham please try the latest `v0.50.5` release. Would also recommend to use Terraform `1.3.x`
