### ISSUE TITLE
The terraform-provider-cloudfoundry_v0.51.1 plugin crashed

### ISSUE THREAD

**Issue by vishwas-philips** [cloudfoundry-community/terraform-provider-cloudfoundry#511]
Stack trace from the terraform-provider-cloudfoundry_v0.51.1 plugin:

panic: interface conversion: interface {} is string, not types.NullString

goroutine 86 [running]:
github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry.ResourceDataToAppDeployV3(_)
	github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/structures_app.go:216 +0x1845
github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry.resourceAppUpdate({0x11ba4b0?, 0xc0005fb260?}, 0xc00011a200, {0xf[72](https://github.com/philips-internal/ampm-protocol-execution-system/actions/runs/5552168009/jobs/10139311284#step:16:73)900?, 0xc00017c840?})
	github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/resource_cf_app.go:440 +0x2cc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0003b5260, {0x11ba4b0, 0xc0005fb260}, 0xd?, {0xf72900, 0xc00017c840})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:767 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003b5260, {0x11ba4b0, 0xc0005fb260}, 0xc000590820, 0xc000191980, {0xf72900, 0xc00017c840})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:8[74](https://github.com/philips-internal/ampm-protocol-execution-system/actions/runs/5552168009/jobs/10139311284#step:16:75) +0x845
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00039e090, {0x11ba4b0?, 0xc0005fb140?}, 0xc0006902[80](https://github.com/philips-internal/ampm-protocol-execution-system/actions/runs/5552168009/jobs/10139311284#step:16:81))
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000302b40, {0x11ba4b0?, 0xc0004e4ed0?}, 0xc00071c000)
	github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov5/tf5server/server.go:[82](https://github.com/philips-internal/ampm-protocol-execution-system/actions/runs/5552168009/jobs/10139311284#step:16:83)1 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xffed60?, 0xc000302b40}, {0x11ba4b0, 0xc0004e4ed0}, 0xc000653f80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000f05a0, {0x11bf398, 0xc0003bf1e0}, 0xc0004f[87](https://github.com/philips-internal/ampm-protocol-execution-system/actions/runs/5552168009/jobs/10139311284#step:16:88)e0, 0xc00039b950, 0x1[88](https://github.com/philips-internal/ampm-protocol-execution-system/actions/runs/5552168009/jobs/10139311284#step:16:89)7e80, 0x0)
	google.golang.org/grpc@v1.56.0/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0000f05a0, {0x11bf398, 0xc0003bf1e0}, 0xc0004f87e0, 0x0)
	google.golang.org/grpc@v1.56.0/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.0/server.go:[95](https://github.com/philips-internal/ampm-protocol-execution-system/actions/runs/5552168009/jobs/10139311284#step:16:96)9 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.0/server.go:957 +0x18c

Error: The terraform-provider-cloudfoundry_v0.51.1 plugin crashed!

**Comment by loafoe** [comment]
@vishwas-philips should be fixed in `v0.51.2`

**Comment by vishwas-philips** [comment]
Its working fine, Thank you for the quick fix
