### ISSUE TITLE
service binding failed for the app

### ISSUE THREAD

**Issue by Durgaprasad-Polavarapu** [cloudfoundry-community/terraform-provider-cloudfoundry#533]
We use terraform to provision CF platform serices and apps deployment
   
   cloudfoundry provider : cloudfoundry-community/cloudfoundry v0.51.3
  
  while deploying multiple microservices observing below exception with binding of platform services 
  if we retrigger deployment would susseced, this error is appearing randomly, not specific one app
  
  we are not sure if this exception coming from CF platform or terraform provider (using latest version for provider)
 ╷
│ Error: Binding  failed for app cad-tagging-management, reason: [Job (53ae989b-4f72-4eba-9f9e-01fd1353423d) failed: bind could not be completed: The service broker returned an invalid response. Status Code: 502 Bad Gateway, Body: 502 Bad Gateway: Registered endpoint failed to handle the request.
│ ]
│ 
│   with module.cad-tagging-management.cloudfoundry_app.cf_app,
│   on modules/cfapp/cfapp.tf line 5, in resource "cloudfoundry_app" "cf_app":
│    5: resource "cloudfoundry_app" "cf_app" {

expected output:

 successful binding of services to app

Actual output
 
 Binding  failed for app

**Comment by Thanhphan1147** [comment]
Hi, normally service-broker errors are not related to the provider. usually you'd need to reach out to your platform's operator for this.

**Comment by loafoe** [comment]
@Durgaprasad-Polavarapu as discussed, please raise internal SNOW ticket to have this investigated further
