### ISSUE TITLE
App Deletion with Service Binding to Async Service Broker

### ISSUE THREAD

**Issue by LukasHeimann** [cloudfoundry-community/terraform-provider-cloudfoundry#546]
When **deleting an application**, Cloud Foundry will usually delete a few of the resources that belong to it. For backing services bound to the app, it will call the corresponding service broker to unbind them. However, service brokers may work asynchronously, responding with 202. The current behavior of Cloud Foundry is that in this case the **delete job will fail** and the app will stay up, but the binding will be removed eventually, at which point **deletion should be retried**.

This behavior is honestly a bit strange, and even the core team is looking into that: https://github.com/cloudfoundry/cloud_controller_ng/issues/3589#:~:text=Delete%20app%20when%20bound%20to%20service
Until this is fixed at Cloud Foundry, it would be great if the terraform provider could work around this issue.

A first step would be to actually catch this issue in the blue-green deployment strategy. While `Restage` **polls for delete job completion**, `Deploy` is currently missing this: https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/commit/e5cad9c1d38a32433a72ddf66e68c984d2db7f7b

The proper workaround for the original issue would be to **retry the deletion** a couple of times and fail only then: https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/commit/4e99babff1c39b9a4130aac10aac3213ab3256f7
At the service that is causing problems in my setup, this already works on the first retry.

There is still an open issue with this for the blue-green strategy: the **reversal** of the app deletion is not ideal. With the change as shown in the linked commits, the failure will cause the app to be removed from state, but still be present at cloud foundry (both new and venerable). I don't know if it is possible to show an error in terraform, but not have the resource removed from the state. In any case, the changes linked above are already improving the situation for me, as the main issue with app deletion is solved.

---

I will open a pull-request in a second, but I'm not all too familiar with go, so it would be great if someone could check that the code style is reasonable. I'm also not sure about testing, except for the manual testing of this against my personal cloud foundry project (where we do have an async service broker).

**Comment by LukasHeimann** [comment]
Hi @loafoe, @Thanhphan1147,

it would be great if you could have a look at this and let me know if there's anything I can do from my side :)

Thank you for maintaining the provider!
Lukas

**Comment by LukasHeimann** [comment]
> So what we did was basically a pre-flight script that removes all of the venerable applications / apps that are not in tfstate

I mean, this is something that the provider could do as well as part of bg deployment, and that would make sense to me as well... The deletion, however, even in this script, has the problem described here and probably only works because the bg-deploy-strategy already removed the async bindings...

**Comment by loafoe** [comment]
I'll go ahead and merge the PR, lets keep this issue open and please share experience after the release

**Comment by LukasHeimann** [comment]
Seems like the issue was closed by the PR. I updated the provider today and enabled the blue-green deployment also in the CI/CD environment, and noticed that the issues described in the issues are gone now.

No surprises here, I already tested this in a test environment using development overrides of terraform and a local build of the provider.

Thank you for making this fix possible!
